### ISSUE TITLE
'insert-collection' with empty collection

### ISSUE THREAD

**Issue by xsc** [keechma/entitydb#3]
`insert-collection`starts with [the following condition](https://github.com/keechma/entitydb/blob/master/src/entitydb/core.cljs#L76-L77):

```clojure
(if (and (nil? item) (nil? meta))
  db
  ...)
```

This means that it won't work to change an existing collection to an empty one. I don't think I can use `remove-collection` in this case since it'll remove any metadata attached to the collection.

My workaround here is adding an empty map as the `meta` parameter to `insert-collection` but still I'm very interested in your thoughts on this.

**Comment by retro** [comment]
Yeah, that might be a premature optimization, I think these can be safely removed. I'll try to work on it this week

**Comment by Sohalt** [comment]
Any updates on this?

**Comment by retro** [comment]
@Sohalt @xsc This is fixed in 5e2f60385f3b220d3290d4a45e855dcb787591c5. I've added the `empty-collection` function that can be used for this.

Check out the API here https://github.com/keechma/entitydb/blob/master/test/entitydb/core.cljs#L339-L365

Version 0.1.2 is pushed to Clojars which contains this feature.
